version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-1604:202004-01

machine:
  node:
    version: v12.16.1

jobs:
  test-e2e:
    executor: machine-executor
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test-chrome
orbs:
  node: circleci/node@3.0.0

workflows:
  test_my_app:
    jobs:
      - test-e2e
