version: 2.1

executors:
  my-node-executor:
    docker:
      - image: circleci/node:12.16.1-browsers

jobs:
  test-e2e:
    executor: my-node-executor
    parallelism: 4
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - browser-tools/install-chromedriver
      - run: echo "export CHROMEDRIVER_PATH=$(which chromedriver)" >> $BASH_ENV
      - run: RUN_IN_PARALLEL=1 npm run test-chrome
orbs:
  node: circleci/node@3.0.1
  browser-tools: circleci/browser-tools@1.0.1

workflows:
  test_my_app:
    jobs:
      - test-e2e
